---
title: "Wiskunde voor Statistiek"
subtitle: "H2 - Bewerkingen"
author: "Witek ten Hove"
output: html_notebook
---
<hr>
Deze notebook hoort bij het boek ["Wiskunde voor Statistiek"](https://shop.coutinho.nl/store_nl/wiskunde-voor-statistiek.html) en demonstreert de concepten die hierin worden besproken met behulp van R.
<hr>

Optellen is het resulaat van twee of meerdere optellingen
```{r}

## Een telfunctie
optelling <- function(start, n) {
  resultaat = 0
  
  for(i in 0:n) {
    resultaat <- start * (i == 0) +
                 (resultaat + 1 * (n > 0) - 1 * (n < 0)) * 
                 (i != 0)
    cat(resultaat, " | ")
  }
  cat(" --> ")
  return(resultaat)
}

# getallenlijn van -3 tot +5
optelling(-3, 8)

# 2 + 3
optelling(optelling(0, 2), 3)

# 4 - 6
optelling(optelling(0, 4), -6)

```

Vermenigvuldigen is hetzelfde als herhaald optellen van gelijke termen.
```{r}
vermenigvuldig <- function(n, m) {
  a <- optelling(0, n)
  j <- 1
  
  while(j < m) {
    a <- optelling(a, n)
    j <- j + 1
    }
  return(a)
}

vermenigvuldig(3, 6)

3*6
```

Machtsverheffen is hetzelfde als herhaald vermenigvuldigen van gelijke factoren.

```{r}

macht <- function(n, p) {
  b <- vermenigvuldig(n, 1)
  k <- 1
  
  while(k < p) {
    b <- vermenigvuldig(b, n)
    k <- k + 1
  }
  return(b)
}
macht(2,5)

2^5
```
