---
title: "SAV-bestanden (SPSS) in R"
output: html_notebook
---

In deze notebook wordt besproken hoe je een SPSS-bestand rechtstreeks in R kunt inlezen.<br><br>

#### 1. Gebruik de `foreign` library en de `read.spss()` functie en lees de data in

```{r, message=FALSE, warning=FALSE}
library(foreign)

url <- "https://github.com/witusj/b-cluster/blob/master/notes/data/Data%20woonwensen%20studenten.sav?raw=true"
rawDF <- read.spss(url, to.data.frame = TRUE)
rbind(head(rawDF, 5), tail(rawDF, 5))
```

<br>

#### 2. Beoordeel de kwaliteit van de data

```{r}
str(rawDF)
summary(rawDF)
```

<br>

#### 3. Bewerk de data
In totaal bevat de data `r r <- dim(rawDF)[1]; r` rijen (observaties) en `r k<- dim(rawDF)[2]; k` kolommen (variabelen). Veel variabelen bevatten lege waarden (NA). We kunnen dit nader onderzoeken door de data visueel te beoordelen.

```{r}
library(visdat)
vis_dat(rawDF)
```

De variabele `WoLastnu` bevat `r n <- dim(rawDF[is.na(rawDF$WoLastnu),])[1]; n` NAs (`r round(100*n/r)`%). We kunnen heel makkelijk alle kolommen deselecteren die teveel NAs bevatten.

```{r}
library(tidyverse)
newDF <- rawDF %>% select(which(colMeans(is.na(.)) < 0.5))
summary(newDF)
```

Er zijn nu nog `r m <- dim(newDF)[2]; m` variabelen over.