---
title: "Verschil tussen twee gemiddelden"
output: html_notebook
---

## Ideale dobbelsteen

```{r fig.width=4,fig.height=3}
library(tidyverse)
distFair <- c(1, 2, 3, 4, 5, 6)
sampleFair <- data.frame(result =sample(x = distFair, size = 100000, replace = TRUE))

ggplot(sampleFair) +
  geom_bar(aes(x = result, fill = as.factor(result)), colour = "black") +
  ggtitle(paste("Gemiddelde = ", mean(as.numeric(sampleFair$result)))) +
  theme(legend.position="none")
```

## Dobbelsteen 1

```{r fig.width=4,fig.height=3}
library(tidyverse)
distNF1 <- c(rep(1, 2), rep(2, 3), 3, 4, 5, 6)
sampleNF1 <- data.frame(result = sample(x = distNF1, size = 100000, replace = TRUE))

ggplot(sampleNF1) +
  geom_bar(aes(x = result, fill = as.factor(result)), colour = "black") +
  ggtitle(paste("Gemiddelde = ", mean(as.numeric(sampleNF1$result)))) +
  theme(legend.position="none")

```

## Dobbelsteen 2

```{r fig.width=4,fig.height=3}
library(tidyverse)
distNF2 <- c(1, 2, 3, 4, rep(5, 4), rep(6, 5))
sampleNF2 <- data.frame(result = sample(x = distNF2, size = 100000, replace = TRUE))

ggplot(sampleNF2) +
  geom_bar(aes(x = result, fill = as.factor(result)), colour = "black") +
  ggtitle(paste("Gemiddelde = ", mean(as.numeric(sampleNF2$result)))) +
  theme(legend.position="none")
```


## Boxplot

```{r fig.width=4,fig.height=3}
type <- c(rep("fair", dim(sampleFair)[1]), rep("nf1", dim(sampleNF1)[1]), rep("nf2", dim(sampleNF2)[1]))
totalDF <- data.frame(type = as.factor(type), result = c(sampleFair$result, sampleNF1$result, sampleNF2$result))

ggplot(totalDF, aes(x = type, y = result, colour = type)) +
  geom_boxplot() +
  theme(legend.position="none")
```

